main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

from . import views

app_name = 'main'

urlpatterns = [
        path('index', views.Index.as_view(), name='index'),
        path('login', views.LoginUser.as_view(), name='login'),
        path('logout', views.LogoutUser.as_view(), name='logout'),
        path('register', views.RegisterUser.as_view(), name='register'),
        path('', views.CreateMail.as_view(), name='new_date'),

        path('api/', include('main.api')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templateBS/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models

''' модели для создания пользователя и входа '''
class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Почтовый адрес должен быть задан')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields['is_staff'] = False
        extra_fields['is_superuser'] = False
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('Почтовый адрес', max_length=50, db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    objects = UserManager()

class Mainindex(models.Model):
    get_user_model()
    title = models.CharField('Название', max_length=50)

    class Meta:
        verbose_name = 'Главная'
        verbose_name_plural = 'Главная страница'


class CityMailSend(models.Model):
    city = models.CharField('Город', max_length=60)

    def __str__(self):
        return self.city


class DateMailSend(models.Model):
    city = models.ForeignKey(CityMailSend,  on_delete=models.CASCADE, related_name='city_select')
    user_created = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    date_create = models.DateTimeField(auto_now_add=True)


''' модель со ссылками '''
class UrlsContent(models.Model):
    date_create = models.ForeignKey(DateMailSend, on_delete=models.CASCADE, null=False, related_name='data')
    poster_url = models.URLField('Ссылка на мероприятие', max_length=60)
    name_event = models.CharField('Название мероприятия', max_length=100)
    rate = models.CharField('Возрастной ценз', max_length=4)
    date_event = models.CharField('Дата мероприятия', max_length=20)
    time_event = models.CharField('Время мероприятия', max_length=20)
    venue = models.CharField('Место проведения', max_length=50)
    price = models.CharField('Цена', max_length=20)
    content_text = models.TextField('Описание мероприятия', max_length=300)


    def __str__(self):
        return self.name_event

main/views.py
import logging
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView
from rest_framework.response import Response
from rest_framework.views import APIView

from .models import UrlsContent, Mainindex, CityMailSend, User, DateMailSend
from .form import LoginUserForm, RegisterUserForm
from .services import created_mailing_list
from rest_framework import generics, status, viewsets

from .serializers import UrlsContentSerializer, CityMailSendSerializer, UserSerializer, DateMailSendSerializer, \
    AllUrlSerializer

logger = logging.getLogger(__name__)

''' класс входа по логину '''


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'main/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        return reverse('main:index')


class LogoutUser(LogoutView):
    next_page = reverse_lazy('main:index')


''' класс регистрации на сайте '''


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('main:login')

    def get_context_date(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context


''' класс выбора рассылки '''

''' сделать вид для главной страницы '''
class Index(ListView):
    model = Mainindex
    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Шаблонизатор'
        return context

    # def post(self, *args, **kwargs):
    #     context = {
    #         'formset_poster': self.formset_poster
    #     }
    #
    #     formset_poster = self.PosterFormset(data=self.request.POST)
    #
    #     if formset_poster.is_valid():
    #         content = formset_poster.cleaned_data
    #         with open('json_url.json', 'w', encoding='utf-8') as file:
    #             json.dump(content, file, indent=4)
    #         return redirect(reverse_lazy('main:new_date'))
    #     return self.render_to_response(context)


''' класс ввода ссылок и сборка афиши '''


class CreateMail(TemplateView):
    template_name = 'main/new_date.html'

    def get(self, *args, **kwargs):
        #self.date_poster = created_mailing_list()

        context = {'title': 'Редактрование афиши',
                   'date_poster': 'ssd'
                   }

        return self.render_to_response(context)



""" Блок с API для вывода """
class UrlAPIViews(generics.ListCreateAPIView):
    queryset = UrlsContent.objects.all()
    serializer_class = UrlsContentSerializer


class CityAPIViews(generics.ListCreateAPIView):
    queryset = CityMailSend.objects.all()
    serializer_class = CityMailSendSerializer

class UserAPIViews(generics.ListCreateAPIView):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class DateAPIViews(generics.ListCreateAPIView):
    queryset = DateMailSend.objects.all()
    serializer_class = DateMailSendSerializer


class AllUrlsView(generics.ListAPIView):
    queryset = UrlsContent.objects.all()
    serializer_class = AllUrlSerializer







    

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'main/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main/css/normalize.css' %}" rel="stylesheet">
</head>
<body>
    
<header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <div class="d-flex justify-content-start">
                <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center">
                    <strong>Шаблонизатор</strong>
                </a>
            </div>

            <div class="d-flex justify-content-end">
            {% if request.user.is_authenticated %}

                    <strong class="navbar-brand">{{ user.email }}</strong>
                    <strong class="navbar-brand"> | </strong>
                    <a href="{% url 'main:logout' %}" class="navbar-brand"><strong>Выйти</strong></a>
                {% else %}
                    <a href="{% url 'main:register' %}" class="navbar-brand"><strong>Регистрация</strong></a>
                    <strong class="navbar-brand"> | </strong>
                    <a href="{% url 'main:login' %}" class="navbar-brand"><strong>Войти</strong></a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<main>
    {% block section %}{% endblock section %}
    {% block content %}{% endblock content %}

</main>
</body>
</html>

main/templates/main/index.html
{% load static %}
<!doctype html><html>
<head>
    <meta charset="utf-8">
    <title>Шаблонизатор</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script defer="defer" src="{% static 'main/js/96d910d518f225df091d.js' %}"></script>
    <link href="{% static 'main/css/cf382795d2dcb90a5062.css' %}" rel="stylesheet">
</head>
<body>


</body>

</html>

main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-5" id="featured-3">
    <h2 class="fpb-2 border-bottom">Авторизуйся</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="d-flex flex-column w-50">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Войти на сайт</h1>
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
                <div class="form-floating mb-3">
                    {{ widget }}
                    {{ widget.label_tag }}
                </div>
                    {% if widget.errors %}
                        <ol>
                            {% for error in widget.errors %}
                            <li><strong class="text-danger">{{ error }}</strong></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
            {% endfor %}
            <button class="w-25 btn btn-lg btn-primary" type="submit">Войти</button>
        </form>
    </div>

</div>
{% endblock content %}

main/templates/main/new_date.html
{% load static %}
<!doctype html>

<html lang="ru"><head><meta charset="utf-8">

<title>{% block title %}{{ title }}{% endblock title %}</title>

<meta name="viewport" content="width=device-width,initial-scale=1">

<!--<script defer="defer" src="{% static 'main/js/new_date.js' %}"></script>-->
<script defer="defer" src="{% static 'main/js/96d910d518f225df091d.js' %}"></script>

<!--<link href="{% static 'main/css/new_date.css' %}" rel="stylesheet">-->
<link href="{% static 'main/css/cf382795d2dcb90a5062.css' %}" rel="stylesheet">
</head>
<body>
<div>
    <!-- это как напоминалка что возвращается в json, потом можно ее убрать -->
    <div style="display: none" id="jsonData" data-json="{{ date_poster }}"></div>

</div>
</body>
</html>

main/templates/main/register.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<div class ="container px-4 py-5" id="featured-3">
    <h2 class="fpb-2 border-bottom">Зарегистрируйся</h2>
</div>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="d-flex flex-column w-50">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Введите данные нового пользователя</h1>
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
                <div class="form-floating mb-3">
                    {{ widget }}
                    {{ widget.label_tag }}
                </div>
                    {% if widget.errors %}
                        <ol>
                            {% for error in widget.errors %}
                            <li><strong class="text-danger">{{ error }}</strong></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
            {% endfor %}
            <button class="w-25 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
        </form>
    </div>

</div>
{% endblock content %}